# -*- coding: utf-8 -*-
"""ATMsoftware using Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NstL2Vd337NGvMvsYlEY2WxrxnpaYc8v
"""

while True:
  balance = 10000
  print("    ATM    ")
  print("""
  1)       Balance
  2)       Withdrawal
  3)       Deposit
  4)       Quit
  """)
  try:
    Option= int(input("Enter the option:  "))
  except Exception as e:
    print("Error:", e)
    print("Enter 1,2,3 or 4 only")
    continue
  if Option==1:
    print("Balance: Rs ", balance)
  if Option==2:
    print("Balance: Rs", balance)
    withdrawal= float(input("Enter Withdrawal amount: Rs"))
    if withdrawal >0:
      remainingbalance=(balance-withdrawal)
      print("Remaining Balance: Rs",  remainingbalance)
    elif withdrawal>balance:
      print("Stop Joking Man!!!")
    else:
      print("No withdrwal made")
  if Option==3:
    print("Balance: Rs ", balance)
    if deposit> 0:
      remainingbalance=(balance+deposit)
      deposit= float(input("Enter the amount: Rs"))
      if deposit>0:
        print("Remaining Balance: Rs", remainingbalance)
    else:
      print("No Deposit made")
  if Option==4:
    exit()